### ISSUE TITLE
发送文件，状态一直显示还未开始

### ISSUE THREAD

**Issue by goforu** [compilelife/feiq#3]
不知到如何发送文件。一直显示还未开始。
mac相互之间不能发文件

**Comment by compilelife** [comment]
是发送文件还是发送文件夹？

**Comment by goforu** [comment]
发送文件，mac和windows上飞秋接发文件没问题。mac和mac之间不行

**Comment by compilelife** [comment]
有可能，因为我们这大部分都是windows，项目初衷是可以让mac与windows通过feiq协作。
的确没有测试过mac之间的通信。

**Comment by compilelife** [comment]
已修复

**Comment by goforu** [comment]
在哪里可以下载安装版本呢

**Comment by compilelife** [comment]
https://github.com/compilelife/feiq/releases/download/v1.2/feiq.zip
