### ISSUE TITLE
大神，请问这个项目怎么启动哦

### ISSUE THREAD

**Issue by YL1989** [compilelife/feiq#5]
我下载完代码木有看到有工程啊，都是代码，请教怎么启动哦；

**Comment by compilelife** [comment]
这是一个qt工程，你需要用qtcreator打开后编译。

你也可以直接下载编译好的二进制：https://github.com/compilelife/feiq/releases/download/v1.2/feiq.zip

**Comment by StarCloudes** [comment]
打开提示这个，请先打开【/Users/star/.feiq_setting.ini】设置用户名(user/name)
