### ISSUE TITLE
打不开软件呀

### ISSUE THREAD

**Issue by StarCloudes** [compilelife/feiq#8]
打开提示这个，请先打开【/Users/star/.feiq_setting.ini】设置用户名(user/name)

**Comment by Ewithome** [comment]
怎么开软件  或者说你什么运行代码的？

**Comment by zszen** [comment]
> 打开提示这个，请先打开【/Users/star/.feiq_setting.ini】设置用户名(user/name)

你需要在终端打开操作，因为这个文件是隐藏的

vim ~/.feiq_setting.ini

找到名字那里键入i变成输入模式，填写后点esc，按:wq回车保存退出就可以启动软件了

**Comment by compilelife** [comment]
😊你们成功吸引了我的注意力……

我很好奇，你们现在还在用飞秋？难道其他通信软件不香吗？

如果真有需求的话，我就再回来维护😁

**Comment by zszen** [comment]
> 😊你们成功吸引了我的注意力……
> 
> 我很好奇，你们现在还在用飞秋？难道其他通信软件不香吗？
> 
> 如果真有需求的话，我就再回来维护😁

好啊，这个软件用与不用，并不取决于我们使用者。。。
